language: node_js
node_js:
- 8.2.1
cache: npm
branches:
  only:
  - master
addons:
  ssh_known_hosts: 123.207.16.175
env:
- SERVER_IP_ADDRESS=123.207.16.175
before_install:
- openssl aes-256-cbc -K $encrypted_7f10c3f38dd5_key -iv $encrypted_7f10c3f38dd5_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh -i ./deploy_key ubuntu@123.207.16.175 'cd /home/ubuntu/koa2_scrapy_news && git
  pull origin master && npm i && pm2 restart scrapy'
